package com.wooyoo.learning.model.domain;

import java.math.BigDecimal;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.i_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    private Integer iId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.product_name
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.price
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.counts
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    private Integer counts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.description
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the name of the database column item.i_id
     *
     * @return the name of item.i_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public Integer getiId() {
        return iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the name of the database column item.i_id
     *
     * @param iId the name for item.i_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public void setiId(Integer iId) {
        this.iId = iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the name of the database column item.product_name
     *
     * @return the name of item.product_name
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the name of the database column item.product_name
     *
     * @param productName the name for item.product_name
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the name of the database column item.price
     *
     * @return the name of item.price
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the name of the database column item.price
     *
     * @param price the name for item.price
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the name of the database column item.counts
     *
     * @return the name of item.counts
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the name of the database column item.counts
     *
     * @param counts the name for item.counts
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the name of the database column item.description
     *
     * @return the name of item.description
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the name of the database column item.description
     *
     * @param description the name for item.description
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}