package com.wooyoo.learning.model.domain;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_pay_money
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    private String isPayMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the name of the database column orders.o_id
     *
     * @return the name of orders.o_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the name of the database column orders.o_id
     *
     * @param oId the name for orders.o_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the name of the database column orders.is_pay_money
     *
     * @return the name of orders.is_pay_money
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public String getIsPayMoney() {
        return isPayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the name of the database column orders.is_pay_money
     *
     * @param isPayMoney the name for orders.is_pay_money
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public void setIsPayMoney(String isPayMoney) {
        this.isPayMoney = isPayMoney == null ? null : isPayMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the name of the database column orders.create_time
     *
     * @return the name of orders.create_time
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the name of the database column orders.create_time
     *
     * @param createTime the name for orders.create_time
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the name of the database column orders.user_id
     *
     * @return the name of orders.user_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the name of the database column orders.user_id
     *
     * @param userId the name for orders.user_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}