package com.wooyoo.learning.model.domain;

public class OrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.order_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.order_item_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    private Integer orderItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.item_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the name of the database column order_item.order_id
     *
     * @return the name of order_item.order_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the name of the database column order_item.order_id
     *
     * @param orderId the name for order_item.order_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the name of the database column order_item.order_item_id
     *
     * @return the name of order_item.order_item_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public Integer getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the name of the database column order_item.order_item_id
     *
     * @param orderItemId the name for order_item.order_item_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public void setOrderItemId(Integer orderItemId) {
        this.orderItemId = orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the name of the database column order_item.item_id
     *
     * @return the name of order_item.item_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the name of the database column order_item.item_id
     *
     * @param itemId the name for order_item.item_id
     *
     * @mbggenerated Mon Mar 25 11:54:59 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
}